# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Object-Generic-Session
version:      0.12
version_from: lib/Object/Generic/Session.pm
installdirs:  site
requires:
    Apache::Cookie:                0
    Object::Generic:               0
    Session:                       0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
